target(name='finagle-example',
  dependencies=[
    'finagle/finagle-example/src/main/java',
    'finagle/finagle-example/src/main/scala',
  ]
)

target(name='tests',
  dependencies=[
    'finagle/finagle-example/src/test/scala'
  ]
)
